# Generated by Django 6.0.2 on 2026-02-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(help_text='Original user input (URL or command)')),
                ('script_url', models.URLField(help_text='Resolved script download URL', max_length=2048)),
                ('script_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the script content', max_length=64)),
                ('script_content', models.TextField(help_text='The downloaded script content')),
                ('explanation_md', models.TextField(help_text='LLM-generated explanation (Markdown)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['script_url'], name='analyzer_an_script__e9fee6_idx')],
            },
        ),
    ]
